# Generated by Django 4.1.1 on 2022-10-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_course_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='duration',
            field=models.IntegerField(default=255),
            preserve_default=False,
        ),
    ]
