# Generated by Django 4.1.1 on 2022-10-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_course_details_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='qualification',
        ),
    ]
