# Generated by Django 4.1.1 on 2022-10-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_student_details_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='fee',
            field=models.BigIntegerField(default=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_details',
            name='duration',
            field=models.BigIntegerField(),
        ),
    ]
