# Generated by Django 4.1.1 on 2022-10-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_student_details_course_usermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
