# Generated by Django 4.1.1 on 2022-10-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_alter_usermember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='image',
            field=models.ImageField(default=255, upload_to=''),
            preserve_default=False,
        ),
    ]
